name: 'base'

on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint

  fmt:
    name: fmt
    runs-on: ubuntu-20.04
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: terraform fmt --recursive -check=true

  validate:
    name: validate
    runs-on: ubuntu-20.04
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - name: terraform validate
        run: |
          terraform init
          terraform validate -no-color
        env:
          AWS_DEFAULT_REGION: "eu-central-1"

  tfsec:
    name: TFSec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: TFSec
        uses: triat/terraform-security-scan@v2.0.2
        with:
          tfsec_actions_comment: false
